version: '3'

services:
    laveral-service:
      build:
        context: ./laveral-service
        dockerfile: ./Dockerfile
      image: digitalocean.com/php
      container_name: laveral-service
      restart: unless-stopped
      tty: true
      working_dir: /var/www
      volumes:
        - ./laveral-service:/var/www/laveral
        - ./laveral-service/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      environment:
          - DB_HOST=database
          - REDIS_HOST=redis
      links:
        - mysql
        - redis
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '9000:9000'
      networks:
        - app-network
    
    nginx:
      build:
        context: ./nginx
        dockerfile: ./Dockerfile
      volumes:
        - ./laveral-service:/var/www/laveral
        - ./web-app/dist:/var/www/dist
      links:
        - laveral-service  
      ports:
        - "80:80"
        - "443:443"
        - "8081:8081"
      networks:
        - app-network

    mysql:
      image: mysql
      restart: always
      volumes:
        - dbdata:/var/lib/mysql
        - ./mysql/my.cnf:/etc/my.cnf
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: api_lockhash_io
        MYSQL_USER: dbuser
        MYSQL_PASSWORD: secret
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
      expose:
        # Opens port 3306 on the container
        - '3306'
      networks:
        - app-network
     
    redis:
        image: redis
        ports:
          - "6379"
        networks:
          - app-network
    

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local