version: '3'

services:
    lockhash-18:
      build: 
        context: ./hash-service
        dockerfile: ./Dockerfile
      links:
        - db
      ports:
        - "8080:8080"

    db:
      image: mysql
      restart: always
      environment:
        MYSQL_DATABASE: 'db'
        # So you don't have to use root, but you can if you like
        MYSQL_USER: 'user'
        # You can use whatever password you like
        MYSQL_PASSWORD: 'localtest'
        # Password for root access
        MYSQL_ROOT_PASSWORD: 'localtest'
      ports:
        # <Port exposed> : < MySQL Port running inside container>
        - '3306:3306'
      expose:
        # Opens port 3306 on the container
        - '3306'